slave_forwarder:
  ros__parameters:
    sub_timestamp_topic_name: "timestamp_slave"
    pub_timestamp_topic_name: "timestamp_slave_d"
    sub_delay_truth_topic_name: "tau_ms_truth"
    pub_delay_truth_topic_name: "tau_ms_truth_d"
    sub_delay_remote_estimation_list_topic_name: "tau_ms_estimation_list"
    pub_delay_remote_estimation_list_topic_name: "tau_ms_estimation_list_d"
    # slave site
    sub_joint_state_topic_name: "joint_state"
    pub_joint_state_topic_name: "joint_state_d"
    sub_pose_state_topic_name: "pose_state"
    pub_pose_state_topic_name: "pose_state_d"
    # master site
    sub_joint_command_topic_name: ""
    pub_joint_command_topic_name: ""
    sub_pose_command_topic_name: ""
    pub_pose_command_topic_name: ""
    sub_pose_raw_topic_name: ""
    pub_pose_raw_topic_name: ""

    # delay = A_0 + A_1 * sin(2*pi/T_1*t+Phi_1) + A_2 * cos(2*pi/T_2*t+Phi_2) + A_3*w(0,1)
    # unit ms
    ###########
    # # delay 0
    # A_0: 0
    # A_1: 0
    # A_2: 0
    # A_3: 0
    # T_1: 0
    # T_2: 0
    # Phi_1: 0
    # Phi_2: 0
    ###########
    # delay 1
    A_0: 100
    A_1: 0
    A_2: 0
    A_3: 20
    T_1: 0
    T_2: 0
    Phi_1: 0
    Phi_2: 0
    ###########
    # # delay 2
    # A_0: 300
    # A_1: 0
    # A_2: 0
    # A_3: 20
    # T_1: 0
    # T_2: 0
    # Phi_1: 0
    # Phi_2: 0
    ###########
    # # delay 3
    # A_0: 500
    # A_1: 0
    # A_2: 0
    # A_3: 20
    # T_1: 0
    # T_2: 0
    # Phi_1: 0
    # Phi_2: 0
    ###########
    # # delay 4
    # A_0: 300
    # A_1: 50
    # A_2: 0
    # A_3: 20
    # T_1: 10000
    # T_2: 0
    # Phi_1: 0
    # Phi_2: 0
    ###########
    # # delay 5
    # A_0: 1000
    # A_1: 100
    # A_2: 50
    # A_3: 100
    # T_1: 10000
    # T_2: 20000
    # Phi_1: 0
    # Phi_2: 0
    ###########

